### ISSUE TITLE
Memory leak in CEF GPU process

### ISSUE THREAD

**Issue by mihe** [roche-emmanuel/cef_direct3d_offscreen_rendering#1]
After applying your changes, the GPU process seems to leak a couple of MB per frame for me, resulting in my RAM filling up pretty quickly, especially when viewing something animated. Haven't been able to track down where the leak is coming from exactly yet.

**Comment by roche-emmanuel** [comment]
Hi mihe, actually I noticed that too: I can quickly get my GPU process to use 15GB (or more) by generating a lot of frame per seconds....

... I'm currently investigating this too. if you have any idea on your side, please let me know. From my perspective, I feel this could be due to some kind of problem in the texture release process: if you kept the logging system in place and you set the env. variable **NV_CEF_LOG_LEVEL=2** to generate the "cef_nv.log" I think you could also notice that a lot of new texture ids are generated, but they don't get released "fast enough"... I have to figure out what this is exactly.

**Comment by roche-emmanuel** [comment]
Hello mihe, just in case you would still be running this code on your side, please note that I updated it to fix the issue we discussed here.

And actually, we are now using this implement in production in my company since the CEF behavior is now stable.

Yet, if you haven't done so yet, I would suggest you have a look at the pull request submitted by Isaac Richards on the CEF repo: that implementation is actually simpler than mine here, and thus it is probably the way to go on the long run.

**Comment by mihe** [comment]
Thanks for the update @roche-emmanuel . I've put this whole thing on the backburner for now, so I'm not currently using your changes. As you suggested I'm keeping a close eye on the PR by Isaac Richards to see if it matures enough that we can use it safely.
